### ISSUE TITLE
Add licence files to the root directories

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/tutorial-microprofile#12]
We need to add in any missing licence files in all the root directories of each branch while also adding them into the Java classes at the top of the file.

**Comment by gkertaseferi** [comment]
We need a LICENCE file in the root directory of the repository. Here is an example of what we need https://github.com/OpenLiberty/guide-rest-client-java/blob/master/LICENSE. We also need the eclipse licence at the top of all our source code which you can find here https://github.com/OpenLiberty/guide-rest-client-java/blob/master/LICENSE.

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
