### ISSUE TITLE
Setup gitignore so that IDE generated files are not uploaded.

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/tutorial-microprofile#21]
When using visual studio code and other IDE's  they sometimes generate files that are not required to run the application. Git has a way to address not uploading these files by using the gitignore file that will ignore specified files when uploading to the online repository. This needs to be implemented for the:
.setting dir
target dir
.classpath file and a few others.

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
