### ISSUE TITLE
"Tutorial Theme" section needs a diagram

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/tutorial-microprofile#25]
The Tutorial theme in the main README.md would be easier to follow if there was a diagram showing the services/front-end, etc.

**Comment by jamiecoleman92** [comment]
Could we use the image of each module like we have created in Mural?

**Comment by jamiecoleman92** [comment]
![microprofile image](https://user-images.githubusercontent.com/14291840/34607966-f50461a2-f20d-11e7-9a9a-094ad2a8e26a.png)

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
