### ISSUE TITLE
Theme and service naming.

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/tutorial-microprofile#26]
I'm struggling a bit with the theme and suspect it may just get in the way as you need to understand the theme to then start understanding the services.  I'd be inclined to drop the space theme but could be persuaded.  What do others think?

The theme isn't carried through in that the back-end services are not theme named, they're just numbers or letters, which brings me on to...
... we switch between calling them A and B and 1 and 2, so aren't consistent.

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
