### ISSUE TITLE
Questions about "Information About The Files We Have Provided" section 

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/tutorial-microprofile#29]
It's not clear to me what is important to the reader about this section.  For example:
 - Why do I specifically need to know how to change the application name (we have maven docs/tutorial to cover this)?
- Why do I need to know about the maven build (this might be useful later, but probably not so much here)?
 - Why do I need to know about the server xml (again, this might be useful later, but not so much here)?

I'm happy to keep this is there's a particular reason, but it's not clear from the explanation why a reader should care.

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
