### ISSUE TITLE
Modules README.md could benefit from diagrams

### ISSUE THREAD

**Issue by gcharters** [OpenLiberty/tutorial-microprofile#35]
I think a diagram would be helpful when describing what will be created.  This could be re-used from whatever we create for issue #25

**Comment by jamiecoleman92** [comment]
I have added images to modules 1,2 and 3 but I am waiting for the instructions for the other modules to be merged before continuing with the remaining two.

**Comment by gkwan-ibm** [comment]
close
- the README was refactored
