### ISSUE TITLE
Add microservice endpoints as environment variables

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/tutorial-microprofile#4]
We currently have our endpoints hard coded into the gateway microservice. This needs to be changed so that we specify the endpoints as part of the build (In the pom.xml file) and then the code changed in the gateway to use these environment variables.

**Comment by jamiecoleman92** [comment]
It seems this is not possible to do with a maven build. @gcharters do you have another solution in mind?

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
