### ISSUE TITLE
No code in module 1's README for microservice 2 set-up instructions

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/tutorial-microprofile#48]
There is no code present in the README.md document under the instructions for what to input into the LiberyRestEndpoint.java file. At the moment it simply reads: "NEW CODE TO BE ADDED HERE!!!" I believe this is because we were going to change what information is given by microservice two, which may still be the case but some code needs to be placed here.

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
