### ISSUE TITLE
Need to specify that users need to make their own fork to save to in main README

### ISSUE THREAD

**Issue by GraceJansen** [OpenLiberty/tutorial-microprofile#49]
To allow user's to switch between branches and minimize error messages, user's need to be able to 'save' their progress by pushing them to the branch. In order to do this they need to make their own copies of our branches in their own fork. Otherwise when they try and switch from one branch to another they will be stopped by their terminal because it would result in all of their previous work (through following the instructions of the previous module) to be lost.

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
