### ISSUE TITLE
Investigate new tutorial structure

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/tutorial-microprofile#57]
We have been tasked with turning our tutorial into a set of guides that can be consumed one by one. I am currently investigating the best way we can achieve this.

**Comment by jamiecoleman92** [comment]
![image](https://user-images.githubusercontent.com/14291840/34879741-26a79e66-f7a6-11e7-9655-693ff1aa984e.png)

**Comment by jamiecoleman92** [comment]
So we will most probably end up with 6 Guides. They will all build on the REST, CDI and JSON-P guide and the Config will most probably build upon the Fault tolerance guide as it would be useful to externalise stuff like the backup endpoint etc!

As far as I am aware the REST Guide has been completed so we should have some code to build upon! 

- Then we will need to take that code and add in what is required for Fault Tolerance!

- Then create a guide for fault tolerance.

- Then edit the guide for health so that it builds on the same code as the REST/CDI guide

- Then again build on the code from the REST guide to include Metrics

- Then create a guide for Metrics

- Again build on top of the REST code for JWT

- Create a guide for JWT

- Add code for Config on top of the fault tolerance guide

- Create a guide for fault tolerance.

- Finally create a kind of intro guide to the tutorial that will explain how it is structured etc

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
