### ISSUE TITLE
The front page missed Rest client

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/tutorial-microprofile#62]
The Rest Client guide is missing from the front page.

**Comment by Emily-Jiang** [comment]
@jamiecoleman92 can you fix this quickly?

**Comment by jamiecoleman92** [comment]
I can but I am on 3% battery and at a conference with no plug sockets.

**Comment by yeekangc** [comment]
We don't have a REST client guide yet.  It is a high priority item in progress, which is tracked via https://github.com/OpenLiberty/guides-common/issues/25.

A draft is available at https://github.com/OpenLiberty/draft-guide-microprofile-rest-client.

**Comment by yeekangc** [comment]
@gcharters, the tutorial should be a short lived entity AFAIK.  How long do we need to keep it around or up to date?

**Comment by gkwan-ibm** [comment]
close
- the mp-rest-client guide was published
- the README was refactored to use the OL static guides
