### ISSUE TITLE
Write up instructions for the Health/Metrics module

### ISSUE THREAD

**Issue by jamiecoleman92** [OpenLiberty/tutorial-microprofile#7]
We need to create instructions for module 5 (Health & Metrics). This will include creating the required files, adding the required code and testing that it all works.

**Comment by jamiecoleman92** [comment]
Hey. Can I get an update on your progress on this please. 
Thanks

**Comment by gkwan-ibm** [comment]
close
- the README was refactored to use the OL static guides
